// GENERATED by scripts/gen-admin-tools.mjs — DO NOT EDIT.
//
// One MCP tool definition per `read`/`write`-annotated GurtApi method
// (docs/requirements-session-operator.md §3.2): the schema is derived from
// the parameter types, the description is the JSDoc, the name is the
// method's snake_case, and the leading `ws` parameter is dropped — the host
// binds the operator's own workspace. Regenerate with:
//
//   node scripts/gen-admin-tools.mjs
//
// CI regenerates and asserts an empty diff (scripts/admin-surface.test.mjs).
import { z } from 'zod'
import type { GurtApi } from './api'

export interface AdminToolDef {
  /** MCP tool name — the snake_case of `method`. */
  name: string
  /** The GurtApi method this tool derives from. */
  method: keyof GurtApi
  exposure: 'read' | 'write'
  /** The method's JSDoc, verbatim. */
  description: string
  /** True when the method's leading `ws` parameter is host-bound (§3.2). */
  bindWs: boolean
  /** Remaining parameter names, in call order — how named tool arguments
   *  map back onto the positional method call. */
  params: readonly string[]
  /** zod shape over `params` — what the MCP tool validates. */
  input: z.ZodRawShape
}

export const ADMIN_TOOLS: readonly AdminToolDef[] = [
  {
    name: "get_tree",
    method: "getTree",
    exposure: "read",
    description: "GurtApi.getTree",
    bindWs: false,
    params: [],
    input: {}
  },
  {
    name: "get_mcp_defs",
    method: "getMcpDefs",
    exposure: "read",
    description: "GurtApi.getMcpDefs",
    bindWs: false,
    params: [],
    input: {}
  },
  {
    name: "get_agents",
    method: "getAgents",
    exposure: "read",
    description: "GurtApi.getAgents",
    bindWs: false,
    params: [],
    input: {}
  },
  {
    name: "set_agents",
    method: "setAgents",
    exposure: "write",
    description: "GurtApi.setAgents",
    bindWs: false,
    params: ["agents"],
    input: { "agents": z.record(z.string(), z.strictObject({ "kind": z.string(), "label": z.string(), "credentialId": z.string().optional(), "secretEnv": z.string().optional(), "env": z.record(z.string(), z.string()).optional() })) }
  },
  {
    name: "get_agent_config",
    method: "getAgentConfig",
    exposure: "read",
    description: "Cached (or hardcoded-default) config surface of an agent instance — the\nNew Session modal reads it to offer model/effort/command choices upfront.",
    bindWs: false,
    params: ["agentId"],
    input: { "agentId": z.string() }
  },
  {
    name: "get_credentials",
    method: "getCredentials",
    exposure: "read",
    description: "GurtApi.getCredentials",
    bindWs: false,
    params: [],
    input: {}
  },
  {
    name: "credential_used_by",
    method: "credentialUsedBy",
    exposure: "read",
    description: "Repos (as `ws/repo`) linking to a credential id — for delete-blocking.",
    bindWs: false,
    params: ["id"],
    input: { "id": z.string() }
  },
  {
    name: "add_repo",
    method: "addRepo",
    exposure: "write",
    description: "GurtApi.addRepo",
    bindWs: true,
    params: ["repo"],
    input: { "repo": z.strictObject({ "name": z.string(), "url": z.string(), "credentialId": z.string().optional() }) }
  },
  {
    name: "discover_devcontainer",
    method: "discoverDevcontainer",
    exposure: "read",
    description: "Resolves credentials the same way session clones do (by registered repo,\nhonoring a repo-linked credential), so it works for private repos too.\nWhen the found config has `build.dockerfile`, the companion Dockerfile is\nreturned too — the env editor seeds both fields at once.",
    bindWs: true,
    params: ["repo"],
    input: { "repo": z.string() }
  },
  {
    name: "discover_dockerfiles",
    method: "discoverDockerfiles",
    exposure: "read",
    description: "Dockerfile candidates (with content) from the repo (root +\n`.devcontainer/**`), loaded into the env editor's Dockerfile field —\neditable there after loading, not re-read from the repo.",
    bindWs: true,
    params: ["repo"],
    input: { "repo": z.string() }
  },
  {
    name: "env_image_status",
    method: "envImageStatus",
    exposure: "read",
    description: "Image status of the SAVED env config (badge in Settings → Environments).",
    bindWs: true,
    params: ["env"],
    input: { "env": z.string() }
  },
  {
    name: "env_build_image",
    method: "envBuildImage",
    exposure: "write",
    description: "Pre-build the SAVED env config's image from its default repo's HEAD; the\nbuild log streams over `provision-log` with key `env-build:<ws>/<env>`.",
    bindWs: true,
    params: ["env"],
    input: { "env": z.string() }
  },
  {
    name: "update_repo",
    method: "updateRepo",
    exposure: "write",
    description: "GurtApi.updateRepo",
    bindWs: true,
    params: ["repo"],
    input: { "repo": z.strictObject({ "name": z.string(), "url": z.string(), "credentialId": z.string().optional() }) }
  },
  {
    name: "remove_repo",
    method: "removeRepo",
    exposure: "write",
    description: "GurtApi.removeRepo",
    bindWs: true,
    params: ["name"],
    input: { "name": z.string() }
  },
  {
    name: "add_env",
    method: "addEnv",
    exposure: "write",
    description: "Register an env definition in the workspace.",
    bindWs: true,
    params: ["env"],
    input: { "env": z.strictObject({ "name": z.string(), "devcontainer": z.string(), "dockerfile": z.string().optional(), "dockerfilePath": z.string().optional(), "repo": z.string().optional() }) }
  },
  {
    name: "update_env",
    method: "updateEnv",
    exposure: "write",
    description: "Update an env definition, matched by its (immutable) name.",
    bindWs: true,
    params: ["env"],
    input: { "env": z.strictObject({ "name": z.string(), "devcontainer": z.string(), "dockerfile": z.string().optional(), "dockerfilePath": z.string().optional(), "repo": z.string().optional() }) }
  },
  {
    name: "remove_env",
    method: "removeEnv",
    exposure: "write",
    description: "Remove an env definition (blocked while any session still runs it).",
    bindWs: true,
    params: ["name"],
    input: { "name": z.string() }
  },
  {
    name: "set_default_agent",
    method: "setDefaultAgent",
    exposure: "write",
    description: "Set (or clear, passing `undefined`) the workspace's default agent — used\nto resolve a session created here without an explicit `agent`. Rejects an\nid the workspace's own deny-list already carries.",
    bindWs: true,
    params: ["agentId"],
    input: { "agentId": z.string().optional() }
  },
  {
    name: "set_denied_agents",
    method: "setDeniedAgents",
    exposure: "write",
    description: "Replace the workspace's agent deny-list wholesale (empty = deny nothing).\nRejects a list that would deny the workspace's current default agent.",
    bindWs: true,
    params: ["agentIds"],
    input: { "agentIds": z.array(z.string()) }
  },
  {
    name: "get_mcp_servers",
    method: "getMcpServers",
    exposure: "read",
    description: "The workspace's user-configured MCP servers (§3.1). Built-ins are a\nseparate, code-owned list — see `getMcpDefs`.",
    bindWs: true,
    params: [],
    input: {}
  },
  {
    name: "add_mcp_server",
    method: "addMcpServer",
    exposure: "write",
    description: "Register an MCP server in the workspace. Rejects a reserved or duplicate\nid, a non-http(s) url, or a credential link that is not an mcp-token.",
    bindWs: true,
    params: ["entry"],
    input: { "entry": z.union([z.strictObject({ "kind": z.literal("http").optional(), "id": z.string(), "label": z.string().optional(), "url": z.string(), "headers": z.array(z.strictObject({ "name": z.string(), "value": z.string() })).optional(), "credentialId": z.string().optional() }), z.strictObject({ "kind": z.literal("npm"), "package": z.string(), "version": z.string().optional(), "id": z.string(), "label": z.string().optional(), "args": z.array(z.string()).optional(), "env": z.record(z.string(), z.string()).optional(), "credentialId": z.string().optional(), "credentialEnvVar": z.string().optional() }), z.strictObject({ "kind": z.literal("command"), "command": z.string(), "cwd": z.string().optional(), "id": z.string(), "label": z.string().optional(), "args": z.array(z.string()).optional(), "env": z.record(z.string(), z.string()).optional(), "credentialId": z.string().optional(), "credentialEnvVar": z.string().optional() })]) }
  },
  {
    name: "update_mcp_server",
    method: "updateMcpServer",
    exposure: "write",
    description: "Update an MCP server, matched by its (immutable) id.",
    bindWs: true,
    params: ["entry"],
    input: { "entry": z.union([z.strictObject({ "kind": z.literal("http").optional(), "id": z.string(), "label": z.string().optional(), "url": z.string(), "headers": z.array(z.strictObject({ "name": z.string(), "value": z.string() })).optional(), "credentialId": z.string().optional() }), z.strictObject({ "kind": z.literal("npm"), "package": z.string(), "version": z.string().optional(), "id": z.string(), "label": z.string().optional(), "args": z.array(z.string()).optional(), "env": z.record(z.string(), z.string()).optional(), "credentialId": z.string().optional(), "credentialEnvVar": z.string().optional() }), z.strictObject({ "kind": z.literal("command"), "command": z.string(), "cwd": z.string().optional(), "id": z.string(), "label": z.string().optional(), "args": z.array(z.string()).optional(), "env": z.record(z.string(), z.string()).optional(), "credentialId": z.string().optional(), "credentialEnvVar": z.string().optional() })]) }
  },
  {
    name: "remove_mcp_server",
    method: "removeMcpServer",
    exposure: "write",
    description: "Remove an MCP server (blocked while a session's selection names it).",
    bindWs: true,
    params: ["id"],
    input: { "id": z.string() }
  },
  {
    name: "get_skills",
    method: "getSkills",
    exposure: "read",
    description: "The workspace's skill registry, read off disk\n(`~/.gurt/<ws>/skills/*`, docs/requirements-skills.md §4.1). An entry whose\n`SKILL.md` is unreadable or malformed comes back carrying a `problem`\nrather than being left out — it is still selectable, still deletable, and\nstill the thing the user has to be shown to fix.",
    bindWs: true,
    params: [],
    input: {}
  },
  {
    name: "get_skill_doc",
    method: "getSkillDoc",
    exposure: "read",
    description: "The one skill's `SKILL.md`, verbatim — what the editor opens.",
    bindWs: true,
    params: ["name"],
    input: { "name": z.string() }
  },
  {
    name: "add_skill",
    method: "addSkill",
    exposure: "write",
    description: "Create a skill directory with this `SKILL.md`. Rejects a bad or duplicate\nname, and a document whose frontmatter does not carry a matching `name`\nand a `description`.",
    bindWs: true,
    params: ["name","doc"],
    input: { "name": z.string(), "doc": z.string() }
  },
  {
    name: "update_skill",
    method: "updateSkill",
    exposure: "write",
    description: "Rewrite a skill's `SKILL.md`, matched by its (immutable) name — renaming\nis not supported, the name is what a session's selection stores. Supporting\nfiles beside it are untouched.",
    bindWs: true,
    params: ["name","doc"],
    input: { "name": z.string(), "doc": z.string() }
  },
  {
    name: "remove_skill",
    method: "removeSkill",
    exposure: "write",
    description: "Delete a skill directory and everything in it (blocked while a session's\nselection names it).",
    bindWs: true,
    params: ["name"],
    input: { "name": z.string() }
  },
  {
    name: "skill_used_by",
    method: "skillUsedBy",
    exposure: "read",
    description: "Task names with a session selecting this skill — what blocks a delete, and\nwhat the confirm dialog names.",
    bindWs: true,
    params: ["name"],
    input: { "name": z.string() }
  },
  {
    name: "set_default_skills",
    method: "setDefaultSkills",
    exposure: "write",
    description: "Replace the workspace's default-on skill set wholesale (empty = none).\nRejects a name the registry does not hold.",
    bindWs: true,
    params: ["names"],
    input: { "names": z.array(z.string()) }
  },
  {
    name: "set_operator_env",
    method: "setOperatorEnv",
    exposure: "write",
    description: "Point the workspace's operator sessions at one of its own envs, or back\nat the bundled default (`undefined`) — the operator twin of\n`setDefaultAgent` (docs/requirements-session-operator.md §2.2). Rejects\nan env the registry does not hold.",
    bindWs: true,
    params: ["env"],
    input: { "env": z.string().optional() }
  },
  {
    name: "reinstall_mcp_server",
    method: "reinstallMcpServer",
    exposure: "write",
    description: "Reinstall an `npm` entry's package: drops the install stamp, so the next\nstart resolves the spec against the registry again instead of reusing what\nis already under `~/.gurt/mcp/<id>/`.\n\nThis is the button behind `version: 'latest'` — the pin is deliberate\n(docs/requirements-mcp-stdio.md §4.2), so \"get a newer latest\" has to be\nsomething the user asks for. Like every other registry change it takes\neffect the next time the server starts; a running process is not restarted\nunder the sessions holding it (§10).",
    bindWs: true,
    params: ["id"],
    input: { "id": z.string() }
  },
  {
    name: "probe_mcp_server",
    method: "probeMcpServer",
    exposure: "read",
    description: "Start this entry the way a session would, speak MCP to it, and report what\nit answered — a local entry is installed, spawned, handshaken and stopped\nagain; a remote one is handshaken with the headers the proxy would send\n(docs/requirements-mcp-stdio.md §4.6).\n\nTakes the whole entry, not an id, because the case it exists for is the\none where there is no id to read yet: the snippet just pasted into the\neditor, checked before it is saved. `ws` addresses the workspace the entry\nbelongs to, like every other method here; nothing about the probe is read\nfrom it — that is what makes an unsaved entry probeable.\n\nNever rejects for the server's own failure: the reason rides in the result\nas a sentence for the user. It rejects only for a broken call.\n\nExplicitly **not** run on save. A local entry executes third-party code on\nthe host with the user's privileges (§2), so running it is a decision the\nuser makes, next to the notice that says so.",
    bindWs: true,
    params: ["entry"],
    input: { "entry": z.union([z.strictObject({ "kind": z.literal("http").optional(), "id": z.string(), "label": z.string().optional(), "url": z.string(), "headers": z.array(z.strictObject({ "name": z.string(), "value": z.string() })).optional(), "credentialId": z.string().optional() }), z.strictObject({ "kind": z.literal("npm"), "package": z.string(), "version": z.string().optional(), "id": z.string(), "label": z.string().optional(), "args": z.array(z.string()).optional(), "env": z.record(z.string(), z.string()).optional(), "credentialId": z.string().optional(), "credentialEnvVar": z.string().optional() }), z.strictObject({ "kind": z.literal("command"), "command": z.string(), "cwd": z.string().optional(), "id": z.string(), "label": z.string().optional(), "args": z.array(z.string()).optional(), "env": z.record(z.string(), z.string()).optional(), "credentialId": z.string().optional(), "credentialEnvVar": z.string().optional() })]) }
  },
  {
    name: "create_task",
    method: "createTask",
    exposure: "write",
    description: "GurtApi.createTask",
    bindWs: true,
    params: ["name"],
    input: { "name": z.string() }
  },
  {
    name: "task_dirty_repos",
    method: "taskDirtyRepos",
    exposure: "read",
    description: "GurtApi.taskDirtyRepos",
    bindWs: true,
    params: ["name"],
    input: { "name": z.string() }
  },
  {
    name: "set_task_max_concurrent_sessions",
    method: "setTaskMaxConcurrentSessions",
    exposure: "write",
    description: "Set/clear the task's cap on concurrently running sessions (undefined or\n0 clears it — unlimited).",
    bindWs: true,
    params: ["name","max"],
    input: { "name": z.string(), "max": z.number().optional() }
  },
  {
    name: "get_task_changes",
    method: "getTaskChanges",
    exposure: "read",
    description: "Git state of every clone of the task, computed on the host; `fetch` reaches the network.",
    bindWs: true,
    params: ["task","opts"],
    input: { "task": z.string(), "opts": z.strictObject({ "fetch": z.boolean().optional() }).optional() }
  },
  {
    name: "get_review_locks",
    method: "getReviewLocks",
    exposure: "read",
    description: "Locked repos of a task, as `repo → true`. A plain read: unlike\n`getReviewState` it never prunes, so the panel can poll it freely.",
    bindWs: true,
    params: ["task"],
    input: { "task": z.string() }
  },
  {
    name: "session_snapshot",
    method: "sessionSnapshot",
    exposure: "read",
    description: "GurtApi.sessionSnapshot",
    bindWs: false,
    params: ["id"],
    input: { "id": z.string() }
  },
  {
    name: "session_traffic",
    method: "sessionTraffic",
    exposure: "read",
    description: "What this session's proxy has been seen doing — the blocked attempts the\nsession pane leads with, and the observed hosts under them\n(docs/requirements-mcp-proxy.md §8). Empty, never absent: a session with\nno proxy yet has observed nothing, which is an answer. Live updates ride\n`proxy-traffic`; this is the pull for a pane that mounted after them.",
    bindWs: false,
    params: ["id"],
    input: { "id": z.string() }
  },
  {
    name: "get_notifications",
    method: "getNotifications",
    exposure: "read",
    description: "In-memory notification history (oldest first) — empty after a relaunch,\nsee docs/requirements-notifications.md §6.",
    bindWs: false,
    params: [],
    input: {}
  },
  {
    name: "get_notification_prefs",
    method: "getNotificationPrefs",
    exposure: "read",
    description: "GurtApi.getNotificationPrefs",
    bindWs: false,
    params: [],
    input: {}
  },
  {
    name: "set_notification_prefs",
    method: "setNotificationPrefs",
    exposure: "write",
    description: "GurtApi.setNotificationPrefs",
    bindWs: false,
    params: ["prefs"],
    input: { "prefs": z.strictObject({ "awaiting": z.strictObject({ "inApp": z.boolean(), "external": z.boolean() }), "proposal": z.strictObject({ "inApp": z.boolean(), "external": z.boolean() }), "error": z.strictObject({ "inApp": z.boolean(), "external": z.boolean() }), "turn-ended": z.strictObject({ "inApp": z.boolean(), "external": z.boolean() }) }) }
  },
  {
    name: "get_hotkeys",
    method: "getHotkeys",
    exposure: "read",
    description: "User overrides for the global keyboard shortcuts, keyed by action —\nan action missing from the stored file uses its built-in default.",
    bindWs: false,
    params: [],
    input: {}
  },
  {
    name: "set_hotkeys",
    method: "setHotkeys",
    exposure: "write",
    description: "GurtApi.setHotkeys",
    bindWs: false,
    params: ["map"],
    input: { "map": z.strictObject({ "palette": z.strictObject({ "code": z.string(), "mod": z.boolean(), "shift": z.boolean(), "alt": z.boolean() }), "newSession": z.strictObject({ "code": z.string(), "mod": z.boolean(), "shift": z.boolean(), "alt": z.boolean() }), "newTask": z.strictObject({ "code": z.string(), "mod": z.boolean(), "shift": z.boolean(), "alt": z.boolean() }), "workspaceNext": z.strictObject({ "code": z.string(), "mod": z.boolean(), "shift": z.boolean(), "alt": z.boolean() }), "workspacePrev": z.strictObject({ "code": z.string(), "mod": z.boolean(), "shift": z.boolean(), "alt": z.boolean() }), "gotoDashboard": z.strictObject({ "code": z.string(), "mod": z.boolean(), "shift": z.boolean(), "alt": z.boolean() }), "gotoTasks": z.strictObject({ "code": z.string(), "mod": z.boolean(), "shift": z.boolean(), "alt": z.boolean() }), "gotoSettings": z.strictObject({ "code": z.string(), "mod": z.boolean(), "shift": z.boolean(), "alt": z.boolean() }) }) }
  },
  {
    name: "get_usage",
    method: "getUsage",
    exposure: "read",
    description: "The retained usage ledger, oldest first — one record per agent turn.\nSurvives relaunches (unlike the notification ring): it is what puts a\nfinished session on the dashboard's DONE column and marks its failures.",
    bindWs: false,
    params: [],
    input: {}
  },
  {
    name: "get_plan_usage",
    method: "getPlanUsage",
    exposure: "read",
    description: "Provider-reported plan limits per agent instance, cached and rate-floored\nin main. Calling this may poll the network; it never rejects for a failed\npoll — the record carries `error` and the previous windows.",
    bindWs: false,
    params: [],
    input: {}
  },
  {
    name: "get_boot_progress",
    method: "getBootProgress",
    exposure: "read",
    description: "Current boot-restore progress — the pull for a window that opened after\nsome `boot-progress` pushes already fired.",
    bindWs: false,
    params: [],
    input: {}
  },
]
